import type { ScenarioMode, ScenarioConfig } from '../types/train';

export const SCENARIOS: Record<ScenarioMode, ScenarioConfig> = {
  normal: {
    id: 'normal',
    label: 'Normal Service',
    description: 'Standard operations across all lines',
    icon: 'activity',
    train_spacing_factor: 1.0,
    event_frequency_multiplier: 1.0,
    tunnel_highlight_intensity: 1.0,
    braking_pulse_enabled: true,
    dwell_variance_enabled: false,
  },
  rush_hour: {
    id: 'rush_hour',
    label: 'Rush Hour Compression',
    description: 'Compressed headways, higher frequency',
    icon: 'zap',
    train_spacing_factor: 0.6,
    event_frequency_multiplier: 1.5,
    tunnel_highlight_intensity: 1.0,
    braking_pulse_enabled: true,
    dwell_variance_enabled: true,
  },
  tunnel_degraded: {
    id: 'tunnel_degraded',
    label: 'Tunnel Relay Degraded',
    description: 'Reduced comms capacity in tunnel zone',
    icon: 'radio',
    train_spacing_factor: 1.3,
    event_frequency_multiplier: 2.0,
    tunnel_highlight_intensity: 2.0,
    braking_pulse_enabled: true,
    dwell_variance_enabled: false,
  },
  bchop_peak: {
    id: 'bchop_peak',
    label: 'B-CHOP Peak Recovery',
    description: 'Maximized regenerative braking events',
    icon: 'battery-charging',
    train_spacing_factor: 1.0,
    event_frequency_multiplier: 2.5,
    tunnel_highlight_intensity: 1.0,
    braking_pulse_enabled: true,
    dwell_variance_enabled: false,
  },
  dwell_delay: {
    id: 'dwell_delay',
    label: 'Station Dwell Delay',
    description: 'Extended station stops system-wide',
    icon: 'clock',
    train_spacing_factor: 1.1,
    event_frequency_multiplier: 1.8,
    tunnel_highlight_intensity: 1.0,
    braking_pulse_enabled: true,
    dwell_variance_enabled: true,
  },
  signal_hold: {
    id: 'signal_hold',
    label: 'Signal Block Hold',
    description: 'Controlled block occupancy management',
    icon: 'shield',
    train_spacing_factor: 1.4,
    event_frequency_multiplier: 1.2,
    tunnel_highlight_intensity: 1.0,
    braking_pulse_enabled: true,
    dwell_variance_enabled: false,
  },
};

export const SCENARIO_ORDER: ScenarioMode[] = [
  'normal',
  'rush_hour',
  'tunnel_degraded',
  'bchop_peak',
  'dwell_delay',
  'signal_hold',
];
